In [2]:
# imports
import numpy as np

**Exercício 1: Soma de Matrizes**

Escreva um programa em Python que soma duas matrizes de mesmo tamanho. As matrizes devem ser lidas como listas e o resultado deve ser exibido na tela. Apresente a solução com e sem uso do Numpy. Pratique suas habilidades de programação ao mesmo tempo que estuda matemática.

In [8]:
def soma_matrizes(matriz_1, matriz_2):
   mat_1 = np.array(matriz_1)
   mat_2 = np.array(matriz_2)

   if mat_1.shape != mat_2.shape:
      raise ValueError("O formato das matrizes precisa ser do mesmo tamanho.")
   
   resultado = mat_1 + mat_2

   return resultado

if __name__ == "__main__":
   matriz_a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   matriz_b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

   resultado = soma_matrizes(matriz_a, matriz_b)

   print("Matriz A: ")
   print(np.array(matriz_a))
   print("\nMatriz B: ")
   print(np.array(matriz_b))
   print("\nResultado (A + B): ")
   print(resultado)

Matriz A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B: 
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Resultado (A + B): 
[[10 10 10]
 [10 10 10]
 [10 10 10]]


**Exercício 2: Multiplicação de Matrizes**

Implemente uma função em Python que multiplica duas matrizes. Verifique se as dimensões das matrizes são compatíveis para a multiplicação e retorne a matriz resultante. Apresente a solução com e sem uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [3]:
import numpy as np

def multiplicar_matrizes(matriz_1, matriz_2):
   mat1 = np.array(matriz_1)
   mat2 = np.array(matriz_2)

   if mat1.shape[1] != mat2.shape[0]:
      raise ValueError(f"Dimensões Incompatíveis: {mat1.shape} x {mat2.shape}")
   
   resultado = np.dot(mat1, mat2)

   return resultado

# Exemplo de Uso

if __name__ == '__main__':
   matriz_a = [[1, 2, 3], [4, 5, 6]]
   matriz_b = [[7, 8], [9, 10], [11, 12]]

   resultado = multiplicar_matrizes(matriz_a, matriz_b)

   print("Matriz A (2x3): ")
   print(np.array(matriz_a))
   print("Matriz B (3x2): ")
   print(np.array(matriz_b))
   print(f"\nResultado (A x B) - (2x2): {resultado}")

   # Exemplo adicional com matrizes quadradas
   print("\n" + "="*40)
   print("Exemplo com matrizes quadradas: ")

   matriz_c = [[1, 2], [3, 4]]
   matriz_d = [[5, 6], [7, 8]]

   resultado2 = multiplicar_matrizes(matriz_c, matriz_d)

   print("\nMatriz C (2x2): ")
   print(np.array(matriz_c))
   print("\nMatriz D (2x2): ")
   print(np.array(matriz_d))
   print("\nResultado (CxD) - (2x2): ")
   print(resultado2)

Matriz A (2x3): 
[[1 2 3]
 [4 5 6]]
Matriz B (3x2): 
[[ 7  8]
 [ 9 10]
 [11 12]]

Resultado (A x B) - (2x2): [[ 58  64]
 [139 154]]

Exemplo com matrizes quadradas: 

Matriz C (2x2): 
[[1 2]
 [3 4]]

Matriz D (2x2): 
[[5 6]
 [7 8]]

Resultado (CxD) - (2x2): 
[[19 22]
 [43 50]]


**Exercício 3: Transposição de Matriz**

Crie um programa que calcula a transposta de uma matriz. A matriz deve ser inserida pelo usuário e o pograma deve exibir a matriz transposta. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda matemática.

In [1]:
import numpy as np

# Calcula a transposta de uma matriz sem usar numpy
def transpor_matriz_manual(matriz):
   linhas = len(matriz)
   colunas = len(matriz[0])

   transposta = [[0 for _ in range(linhas)] for  _ in range(colunas)]

   for i in range(linhas):
      for j in range(colunas):
         transposta[j][i]
   
   return transposta

# Calcula a transposta de uma matriz usando NumPy
def transpor_matriz_numpy(matriz):
   mat = np.array(matriz)
   return mat.T

def exibir_matriz(matriz, nome):
   print(f"\n{nome}: ")
   for linha in matriz:
      print(linha)

def criar_matriz_usuario():
   print("Digite a matriz: ")
   linhas = int(input("Digite a quantidade de linhas: "))
   colunas = int(input("Digite a quantidade de colunas: "))

   matriz = []
   for i in range(linhas):
      linha = []
      for j in range(colunas):
         valor = float(input(f"Elemento [{i}][{j}]: "))
         linha.append(valor)
      matriz.append(linha)
   
   return matriz

# Exemplo de uso
if __name__ == "__main__":
   print("==== EXEMPLO COM MATRIZ PREDEFINIDA ====")
   matriz_exemplo = [[1, 2, 3], [4, 5, 6]]
   print(f"Matriz original (2x3): ")
   exibir_matriz(matriz_exemplo, "Original")

   transposta_numpy = transpor_matriz_numpy(matriz_exemplo)
   print(f"\nTransposta (com NumPy): ")
   print(transposta_numpy)

   print("\n" + "=" * 50)
   print("==== TESTE COM SUA PRÓPRIA MATRIZ ====")
   print("\n==== EXEMPLO COM MATRIZ QUADRADA ====")
   
   matriz_quadrada = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   exibir_matriz(matriz_quadrada, "Matriz quadrada (3x3)")
   transposta_quad = transpor_matriz_manual(matriz_quadrada)
   exibir_matriz(transposta_quad, "Transposta (3x3)")

==== EXEMPLO COM MATRIZ PREDEFINIDA ====
Matriz original (2x3): 

Original: 
[1, 2, 3]
[4, 5, 6]

Transposta (com NumPy): 
[[1 4]
 [2 5]
 [3 6]]

==== TESTE COM SUA PRÓPRIA MATRIZ ====

==== EXEMPLO COM MATRIZ QUADRADA ====

Matriz quadrada (3x3): 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Transposta (3x3): 
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]


**Exercício 4: Traço de uma Matriz**

Desenvolva um script em Python que calcula o traço de uma matriz (soma de elementos da diagonal principal). O programa deve funcionar para matrizes quadradas de qualquer tamanho. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [1]:
import numpy as np

# Calcula o traço de uma matriz quadrada sem usar NumPy]
# O traço é a soma dos elementos da diagonal principal
def calcular_traco_manual(matriz):
   linhas = len(matriz)
   colunas = len(matriz[0])

   if linhas != colunas:
      raise ValueError("A matriz deve ser quadrada para calcular o traço")
   
   traco = 0
   for i in range(linhas):
      traco += matriz[i][i]
   
   return traco

# Calcula a traço de uma matriz usando NumPy
def calcular_traco_numpy(matriz):
   mat = np.array(matriz)

   if mat.shape[0] != mat.shape[1]:
      raise ValueError("A matriz deve ser quadrada para calcular o traço")
   return np.trace(mat)

def exibir_matriz_com_diagonal(matriz):
   print("Matriz: ")
   for i, linha in enumerate(matriz):
      linha_str = ""
      for j, elemento in enumerate(linha):
         if i == j:
            linha_str += f"[{elemento:4}]"
         else:
            linha_str += f"{elemento:4}"

def criar_matriz_quadrado_usuario():
   tamanho = int(input("Digite o tamanho da matriz quadrada (n x n): "))

   matriz = []
   print(f"\nDigite os elementos da matriz {tamanho}x{tamanho}:")

   for i in range(tamanho):
      linha = []
      for j in range(tamanho):
         valor = float(input(f"Elemento [{i}][{j}]: "))
         linha.append(valor)
      matriz.append(linha)
   
   return matriz

# Exemplo de uso
if __name__ == "__main__":
   print("=== EXEMPLO 1: MATRIZ 2X2 ===")
   matriz_2x2 = [[1, 2], [3, 4]]
   exibir_matriz_com_diagonal(matriz_2x2)

   traco_manual = calcular_traco_manual(matriz_2x2)
   traco_numpy = calcular_traco_numpy(matriz_2x2)

   print(f"\nTraço (sem NumPy): {traco_manual}")
   print(f"Traço (com NumPy): {traco_numpy}")
   print(f"Cálculo: {matriz_2x2[0][0]} + {matriz_2x2[1][1]} = {traco_manual}")

   print("\n" + "=" * 50)
   print("=== EXEMPLO 2: MATRIZ 3X3 ===")

   matriz_3x3 = [[1, 2, 3], [3, 4, 5], [7, 8, 9]]
   exibir_matriz_com_diagonal(matriz_3x3)

   traco_manual_3x3 = calcular_traco_manual(matriz_3x3)
   traco_numpy_3x3 = calcular_traco_numpy(matriz_3x3)

   print(f"\nTraço (sem NumPy) {traco_manual_3x3}")
   print(f"Traço (com NumPy): {traco_numpy_3x3}")
   print(f"Cálculo: {matriz_3x3[0][0]} + {matriz_3x3[1][1]} + {matriz_3x3[2][2]} = {traco_manual_3x3}")

   print("\n" + "=" * 50)
   print("=== EXEMPLO 3: MATRIZ IDENTIDADE 4X4 ===")

   matriz_identidade = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
   exibir_matriz_com_diagonal(matriz_identidade)

   traco_identidade = calcular_traco_manual(matriz_identidade)
   print(f"\nTraço da matriz identidade: {traco_identidade}")
   print("(O traço de uma matriz identidade nxn sempre é igual a n)")

   print("\n" + "="*50)
   print("=== TESTE COM SUA PRÓPRIA MATRIZ ===")

   # Exemplo de erro com matreiz não-quadrada
   print("\n=== EXEMPLO DE ERRO ===")
   try:
      matriz_nao_quadrada = [[1, 2, 3], [4, 5, 6]]
      calcular_traco_manual(matriz_nao_quadrada)
   except ValueError as e:
      print(f"Erro capturado: {e}")

=== EXEMPLO 1: MATRIZ 2X2 ===
Matriz: 

Traço (sem NumPy): 5
Traço (com NumPy): 5
Cálculo: 1 + 4 = 5

=== EXEMPLO 2: MATRIZ 3X3 ===
Matriz: 

Traço (sem NumPy) 14
Traço (com NumPy): 14
Cálculo: 1 + 4 + 9 = 14

=== EXEMPLO 3: MATRIZ IDENTIDADE 4X4 ===
Matriz: 

Traço da matriz identidade: 4
(O traço de uma matriz identidade nxn sempre é igual a n)

=== TESTE COM SUA PRÓPRIA MATRIZ ===

=== EXEMPLO DE ERRO ===
Erro capturado: A matriz deve ser quadrada para calcular o traço


**Exercício 5: Determinante de uma Matriz (Desafio)**

Escreva uma função que calcula o determinante de uma matriz quadrada. Utilize e recursividade ou o método de Laplace para calcular o determinante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [2]:
import numpy as np

# SOLUÇÃO SEM NUMPY (RECURSIVA)
def determinante_manual(matriz):
   n = len(matriz)

   if n == 1:
      return matriz[0][0]

   if n == 2:
      return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]
   
   det = 0
   for j in range(n):
      submatriz = [linha[:j] + linha[j+1:] for linha in matriz[1:]]
      cofator = (-1) ** j * matriz[0][j]
      det += cofator * determinante_manual(submatriz)
   
   return det

# SOLUÇÃO COM NUMPY
def determinante_numpy(matriz):
   return np.linalg.det(np.array(matriz))

# EXEMPLOS
if __name__ == "__main__":
   mat_2x2 = [[3, 1], [2, 4]]
   print("Matriz 2x2:")
   print(mat_2x2)
   print(f"Determinante manual: {determinante_manual(mat_2x2)}")
   print(f"Determinante NumPy: {determinante_numpy(matriz_3x3):.0f}")

   mat_3x3 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
   print(f"\nMatriz 3x3:")
   print(mat_3x3)
   print(f"Determinante manual: {determinante_manual(mat_3x3)}")
   print(f"Determinante NumPy: {determinante_numpy(mat_3x3):.0f}")

   mat_singular = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

   print(f"\nMatriz singular:")
   print(mat_singular)
   print(f"Determinante: {determinante_manual(mat_singular)}")
   print("(det = 0 -> matriz não invertível)")

Matriz 2x2:
[[3, 1], [2, 4]]
Determinante manual: 10
Determinante NumPy: -0

Matriz 3x3:
[[1, 2, 3], [0, 1, 4], [5, 6, 0]]
Determinante manual: 1
Determinante NumPy: 1

Matriz singular:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Determinante: 0
(det = 0 -> matriz não invertível)
